{
 "title": "PGCAT Schema",
 "description": "PostgreSQL Catalog Explorer for Single Database",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn:text}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn:text}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn:text}';" },
   {
    "name": "schema",
    "label": "Schema",
    "query": "SELECT nspname FROM pg_namespace;"
   },
   {
    "name": "nspid",
    "label": "SchemaID",
    "query": "SELECT oid FROM pg_namespace WHERE nspname = '$schema';"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Schema",
        "type": "string",
        "values": [ "${schema}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "Schemas of current database ${datname}",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n       relnamespace AS \"OID\", nspname AS \"Schema\", nspowner::RegRole::TEXT AS \"Owner\",\n       coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT relnamespace, json_object_agg(kind, count) AS data\n         FROM (SELECT relnamespace, relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY relnamespace,relkind) d\n         GROUP BY relnamespace\n     ) j LEFT JOIN pg_namespace nsp ON j.relnamespace = nsp.oid\nWHERE nspname NOT IN ('pg_toast', 'information_schema', 'pg_catalog');"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "select unnest(nspacl) from pg_namespace WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT json_object_agg(kind, count) AS data\n         FROM (SELECT relkind::TEXT AS kind, count(*) AS count FROM pg_class \n         WHERE relnamespace = '$nspid'\n         GROUP BY relkind) d\n     ) j;"
    }
   ]
  },
  {
   "title": "Class",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "SELECT * FROM pg_class;",
     "rawSql": "SELECT \n*, '$schema' || '.' || relname AS \"Name\", relowner::RegRole AS \"Owner\",\npg_relation_size(oid) AS Size, age(relfrozenxid) AS age\nFROM pg_class\nWHERE relnamespace = '$nspid';"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Tables",
   "type": "table",
   "description": "Tables of current database ${datname}",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "SELECT * FROM pg_class;",
     "rawSql": "SELECT c.oid,\n       n.nspname,\n       n.nspname || '.' || c.relname                        AS name,\n       CASE WHEN relispartition THEN 'P' ELSE c.relkind END AS kind,\n       age(c.relfrozenxid)::FLOAT / 2147483648              AS relage,\n       (n_tup_ins + n_tup_upd + n_tup_del)                  AS n_tup_mod,\n       seq_scan + idx_scan                                  AS tbl_scan,\n       seq_tup_read + idx_tup_fetch                         AS tup_read,\n       reltuples,\n       relpages,\n       relfilenode,\n       pg_table_size(c.oid)                                 AS size,\n       relnatts,\n       s.seq_scan,\n       s.seq_tup_read,\n       s.idx_scan,\n       s.idx_tup_fetch,\n       s.n_tup_ins,\n       s.n_tup_upd,\n       s.n_tup_del,\n       s.n_tup_hot_upd,\n       -- s.n_tup_newpage_upd, -- PG16\n       s.n_live_tup,\n       s.n_dead_tup,\n       s.n_mod_since_analyze,\n       -- s.n_ins_since_vacuum, -- PG13\n       extract(EPOCH FROM s.last_vacuum) * 1000             AS last_vacuum,\n       extract(EPOCH FROM s.last_autovacuum) * 1000         AS last_autovacuum,\n       extract(EPOCH FROM s.last_analyze) * 1000            AS last_analyze,\n       extract(EPOCH FROM s.last_autoanalyze) * 1000        AS last_autoanalyze,\n       s.vacuum_count,\n       s.autovacuum_count,\n       s.analyze_count,\n       s.autoanalyze_count\nFROM pg_catalog.pg_class c\n         LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n         LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid\nWHERE c.relkind IN ('r', 'p', '')\n  AND schemaname = '$schema'\nORDER BY 1, 2;\n\n\n"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Indexes",
   "type": "table",
   "description": "Read = Returned Rows\n\nFetch = Scanned Rows",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT schemaname || '.' || indexrelname AS \"Index\", \n       schemaname || '.' || relname AS \"Table\", \n       *,\n       pg_get_indexdef(indexrelid) AS def\nFROM pg_stat_user_indexes\nWHERE schemaname = '$schema';"
    }
   ]
  },
  { "title": "Bloat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Table Bloat",
   "type": "table",
   "description": "Bloat ratio & wasted bytes estimation of all heap tables",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "title": "Table Wasted Bytes",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "title": "Index Bloat",
   "type": "table",
   "description": "Bloat ratio & wasted bytes estimation of all btree indexes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "title": "Index Wasted Bytes",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat WHERE nspname = '$schema';"
    }
   ]
  },
  {
   "title": "Seq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || sequencename AS \"Sequence\",  *\nFROM pg_sequences\nWHERE schemaname = '$schema';"
      }
     ]
    }
   ]
  },
  {
   "title": "Extension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Installed Extensions",
     "type": "table",
     "description": "Installed Extension in this Schema",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "SELECT * FROM pg_class;",
       "rawSql": "SELECT e.extname , e.extversion, n.nspname, c.description\nFROM pg_catalog.pg_extension e LEFT JOIN pg_catalog.pg_namespace n\nON n.oid = e.extnamespace LEFT JOIN pg_catalog.pg_description c\nON c.objoid = e.oid AND c.classoid = 'pg_catalog.pg_extension'::pg_catalog.regclass\nWHERE n.nspname = '$schema'\nORDER BY 1;"
      }
     ]
    }
   ]
  }
 ]
}