{
 "title": "PGCAT Locks",
 "description": "PostgreSQL Catalog : Activity & Locks",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn:text}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn:text}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn:text}';" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid::INTEGER, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Locks for ${datname}",
   "type": "table",
   "description": "Block by : Which pid are blocked by this PID ?\n\nBlock N: how many process are blocked by this process?",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "with recursive\n    activity as (select pg_blocking_pids(pid) blocked_by, *,\n                        extract(seconds FROM age(clock_timestamp(), xact_start)) as xact_wait,\n                        extract(seconds FROM age(clock_timestamp(),\n                            -- (select max(l.waitstart) from pg_locks l where a.pid = l.pid)    -- PG 14 and newer\n                             state_change       -- PG 13 and below\n                            )) as lock_wait\n                 from pg_stat_activity a\n                 where state is distinct from 'idle'),\n    blockers as (select array_agg(distinct c order by c) as pids\n                 from (select unnest(blocked_by)\n                       from activity) as dt(c)),\n    tree as (select activity.*,\n                    1                           as level,\n                    activity.pid                as top_blocker_pid,\n                    array [activity.pid]        as path,\n                    array [activity.pid]::int[] as all_blockers_above\n             from activity, blockers\n             where array [pid] <@ blockers.pids and blocked_by = '{}'::int[]\n             union all\n             select activity.*,\n                    tree.level + 1 as level,\n                    tree.top_blocker_pid,\n                    path || array [activity.pid] as path,\n                    tree.all_blockers_above || array_agg(activity.pid) over () as all_blockers_above\n             from activity,\n                  tree\n             where not array [activity.pid] <@ tree.all_blockers_above\n               and activity.blocked_by <> '{}'::int[]\n               and activity.blocked_by <@ tree.all_blockers_above)\nselect pid,\n       blocked_by,\n       case when wait_event_type = 'Lock' then 'waiting' else state end                                      as state,\n       wait_event_type,\n       wait_event,\n       xact_wait,\n       lock_wait,\n       age(backend_xid) AS xid_age,\n       -- 2147483647 - age(backend_xmin) as xmin_ttf,\n       datname, usename, level - 1 AS level,\n       (select count(distinct t1.pid) from tree t1 where array [tree.pid] <@ t1.path and t1.pid <> tree.pid) as blkd,\n       format('%s %s%s', lpad('[' || pid::text || ']', 9, ' '), repeat('.', level - 1) || case when level > 1 then ' ' end, left(query, 1000) ) as query\nfrom tree\nWHERE datname = CURRENT_DATABASE()\norder by top_blocker_pid, level, pid;"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Activity",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT pg_blocking_pids(pid) AS blocking_pids,\n       datid,\n       datname,\n       pid,\n       leader_pid,\n       usesysid,\n       usename,\n       application_name,\n       client_addr,\n       client_hostname,\n       client_port,\n       extract(epoch from now() - backend_start) AS conn_time,\n       extract(epoch from now() - xact_start)    AS xact_time,\n       extract(epoch from now() - query_start)   AS query_time,\n       extract(epoch from now() - state_change)  AS state_time,\n       wait_event_type, wait_event,\n       state,\n       backend_xid,\n       backend_xmin,\n       query_id,\n       query,\n       backend_type,\n       query_id::TEXT AS qid -- 14 has query_id, comment this for PG 13 and below \nFROM pg_stat_activity\nWHERE datname = current_database()\nORDER BY state,wait_event_type;"
    }
   ]
  },
  {
   "title": "WaitEvent (pg_wait_sampling required)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Wait Event History (latest 100)",
     "type": "table",
     "description": "Get the latest 100 record from monitor.pg_wait_sampling_history.",
     "gridPos": { "h": 18, "w": 9, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT * FROM monitor.pg_wait_sampling_history ORDER BY ts DESC LIMIT 100;"
      }
     ]
    },
    {
     "title": "Wait Event Counter",
     "type": "table",
     "description": "agg from monitor.pg_wait_sampling_profile by event_type, event",
     "gridPos": { "h": 18, "w": 5, "x": 9, "y": 36 },
     "targets": [
      {
       "rawSql": "select event_type AS event_type, event, sum(count) AS count  from monitor.pg_wait_sampling_profile GROUP BY event_type, event ORDER BY 3 DESC;"
      }
     ]
    },
    {
     "title": "Wait Event Count in Last 1 second",
     "type": "table",
     "description": "agg from monitor.pg_wait_sampling_profile by event_type, event in last one second",
     "gridPos": { "h": 18, "w": 5, "x": 14, "y": 36 },
     "targets": [
      {
       "rawSql": "  SELECT event_type, event, count(*) FROM monitor.pg_wait_sampling_history \n  WHERE ts BETWEEN now() - '1s'::INTERVAL AND now()\n  GROUP BY 1,2;"
      }
     ]
    },
    {
     "title": "Wait Event Type",
     "type": "piechart",
     "gridPos": { "h": 18, "w": 5, "x": 19, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT now() AS time, \n  coalesce(event_type, 'Running') AS metric, count(*) AS value\n  FROM monitor.pg_wait_sampling_history \n  WHERE ts BETWEEN now() - '1s'::INTERVAL AND now()\n  GROUP BY 2;"
      }
     ]
    },
    {
     "title": "Backends by Wait Event Type",
     "type": "timeseries",
     "description": "Group by pg_stat_activity.wait_event_type on instance level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum by (event) (pg_wait_count{ins=\"$ins\"})",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "Backends by Wait Event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum by (event) (rate(pg_wait_event_count{ins=\"$ins\"}[30s]))",
       "legendFormat": "{{ event }}"
      }
     ]
    }
   ]
  }
 ]
}