apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tradehub-ingress
  namespace: tradehub
spec:
  tls:
    - hosts:
        - tradehub.example.com
      secretName: tradehub-prod-tls
  rules:
    - host: tradehub.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tradehub-api
                port:
                  number: 80
