address: :7373
admin:
  identity: disabled
tls:
  key: /certs/kes.key
  cert: /certs/kes.crt
policy:
  tradehub:
    allow:
      - /v1/key/create/*
      - /v1/key/generate/*
      - /v1/key/decrypt/*
      - /v1/key/encrypt/*
      - /v1/key/list/*
      - /v1/key/describe/*
      - /v1/status
keystore:
  fs:
    path: /kes-data/keys
