{
 "title": "Inventory CMDB",
 "description": "Pigsty Inventory CMDB Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('admin_ip', 'version', 'region');"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 5, "y": 1 },
   "targets": [
    { "rawSql": "SELECT cls FROM pigsty.group" }
   ]
  },
  {
   "title": "Portals",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.key                  AS name,\n       d.value ->> 'domain'   AS domain,\n       replace(d.value ->> 'endpoint', '${admin_ip}', pigsty.get_param('admin_ip') ) AS endpoint\nFROM pigsty.global_config v,\n     jsonb_each(v.value) d\nWHERE v.key = 'infra_portal';"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT key AS ip, (value ->> 'infra_seq')::INTEGER AS infra_seq, \n       'infra-' || (value ->> 'infra_seq') AS name\nFROM pigsty.group_config gc, jsonb_each(gc.hosts)\nWHERE cls = 'infra';"
    }
   ]
  },
  {
   "title": "Etcd Cluster",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT seq, ip, ins FROM pigsty.etcd_instance;"
    }
   ]
  },
  { "title": "PGSQL Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "PGSQL Clusters",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.pg_cluster"
    }
   ]
  },
  { "title": "PGSQL Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "PGSQL Instance",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.pg_instance"
    }
   ]
  },
  { "title": "PGSQL Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "PGSQL Service",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "    SELECT cls,\n           cls || '-' || (value ->> 'name') AS svc,\n           value ->> 'name'                 AS name,\n           value ->> 'ip'                   AS src_ip,\n           value ->> 'port'                 AS src_port,\n           value ->> 'dest'                 AS dst_port,\n           value ->> 'check'                AS check_url,\n           value ->> 'selector'             AS selector,\n           value ->> 'backup'               AS selector_backup,\n           (value ->> 'maxconn')::INTEGER   AS maxconn,\n           (value ->> 'balance')            AS balance,\n           (value ->> 'options')            AS options,\n           value                            AS service\n    FROM pigsty.pg_cluster, jsonb_array_elements(pg_services) ORDER BY 1 ,3;"
    }
   ]
  },
  { "title": "PGSQL Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "PGSQL Database",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.pg_database;"
    }
   ]
  },
  { "title": "REDIS Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "REDIS Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.redis_cluster"
    }
   ]
  },
  {
   "title": "REDIS Instance",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.redis_instance"
    }
   ]
  },
  {
   "title": "REDIS Node",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.redis_node;"
    }
   ]
  },
  { "title": "DNS / Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  to_json(value) #>> '{}' AS \"DNS Enabled\" FROM pigsty.global_config WHERE key = 'dns_enabled';"
    }
   ]
  },
  {
   "title": "DNS Records",
   "type": "table",
   "description": "Dynamic DNS records to be resolved by DNSMASQ on infra nodes",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) record\nWHERE v.key = 'dns_records';"
    }
   ]
  },
  {
   "title": "/etc/resolv.conf",
   "type": "table",
   "description": "Local DNS Configuration to be added to all nodes",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_dns_options'\nUNION ALL\nSELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_dns_servers';"
    }
   ]
  },
  {
   "title": "/etc/hosts",
   "type": "table",
   "description": "Static records to be added to all nodes",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_default_etc_hosts'\nUNION ALL\nSELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_etc_hosts';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  to_json(value) #>> '{}' AS \"Node DNS Method\" FROM pigsty.global_config WHERE key = 'node_dns_method';"
    }
   ]
  },
  { "title": "Repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Nginx / Repo Address",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('nginx_port', 'nginx_sslmode', 'nginx_home', 'nginx_port', 'nginx_ssl_port', 'repo_name');"
    }
   ]
  },
  {
   "title": "Repo Packages",
   "type": "table",
   "gridPos": { "h": 23, "w": 4, "x": 20, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_packages'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_extra_packages';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('repo_enabled', 'repo_modules', 'repo_remove','node_repo_modules', 'node_repo_remove');"
    }
   ]
  },
  {
   "title": "Repo Upstream",
   "type": "table",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 94 },
   "targets": [
    {
     "rawSql": "SELECT d ->> 'name'        AS name,\n       d ->> 'module'      AS module,\n       d ->> 'releases'    AS releases,\n       d ->> 'arch'        AS arch,\n       d ->> 'description' AS description,\n       d -> 'baseurl'      AS baseurl\nFROM pigsty.global_config v,\n     jsonb_array_elements(v.value) d\nWHERE v.key = 'repo_upstream';"
    }
   ]
  },
  { "title": "Packages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Node Packages",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_default_packages'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_packages';"
    }
   ]
  },
  {
   "title": "Infra Packages",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'infra_packages'\nUNION ALL\nSELECT to_json(value) #>> '{}' AS \"DCS Type\" FROM pigsty.global_config WHERE key = 'node_pip_packages';"
    }
   ]
  },
  {
   "title": "PGSQL Packages",
   "type": "table",
   "description": "PostgreSQL Main Packages to be installed (global default)\n\nAlias will be translated according to package_map",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "rawSql": "WITH ver AS (SELECT  to_json(value) #>> '{}' AS \"version\" FROM pigsty.global_config WHERE key = 'pg_version' LIMIT 1)\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_packages'\nUNION ALL\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_extensions'"
    }
   ]
  },
  {
   "title": "PGSQL Extensions",
   "type": "table",
   "description": "PostgreSQL Extension Packages to be installed (global default)\n\nAlias will be translated according to package_map",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "rawSql": "WITH ver AS (SELECT  to_json(value) #>> '{}' AS \"version\" FROM pigsty.global_config WHERE key = 'pg_version' LIMIT 1)\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_extensions';"
    }
   ]
  },
  {
   "title": "Package Map",
   "type": "table",
   "description": "Translate package alias into real package names. $v will be replaced with pg major version",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pigsty.package_map;"
    }
   ]
  }
 ]
}