apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradehub-staging-app
  namespace: argocd
spec:
  project: tradehub
  source:
    repoURL: https://github.com/REPLACE_GITHUB_ORG/TD.2.ANTIGRAVITY.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: tradehub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
