import { z } from "zod";
import * as base from "./schema.pg.base";
import * as audit from "./schema.pg.audit";
import * as identity from "./schema.pg.identity";
import * as grift from "./schema.pg.grift";
import * as legal from "./schema.pg.legal";

export * from "./schema.pg.base";
export * from "./schema.pg.recruitment";
export * from "./schema.pg.audit";
export * from "./schema.pg.identity";
export * from "./schema.pg.grift";
export * from "./schema.pg.legal";

// Types
export type User = typeof base.users.$inferSelect;
export type InsertUser = z.infer<typeof base.insertUserSchema>;
export type SymbolConfig = typeof base.symbolConfigs.$inferSelect;
export type InsertSymbolConfig = z.infer<typeof base.insertSymbolConfigSchema>;
export type TraderQuotePref = typeof base.traderQuotePrefs.$inferSelect;
export type InsertTraderQuotePref = z.infer<typeof base.insertTraderQuotePrefSchema>;
export type TraderQuoteSubscription = typeof base.traderQuoteSubscriptions.$inferSelect;
export type InsertTraderQuoteSubscription = z.infer<typeof base.insertTraderQuoteSubscriptionSchema>;
export type QuoteSubscriptionConfig = typeof base.quoteSubscriptionConfig.$inferSelect;
export type InsertQuoteSubscriptionConfig = z.infer<typeof base.insertQuoteSubscriptionConfigSchema>;
export type Trade = typeof base.trades.$inferSelect;
export type InsertTrade = z.infer<typeof base.insertTradeSchema>;
export type UserSettings = typeof base.userSettings.$inferSelect;
export type InsertUserSettings = z.infer<typeof base.insertUserSettingsSchema>;
export type MailboxThread = typeof base.mailboxThreads.$inferSelect;
export type InsertMailboxThread = z.infer<typeof base.insertMailboxThreadSchema>;
export type MailboxMessage = typeof base.mailboxMessages.$inferSelect;
export type InsertMailboxMessage = z.infer<typeof base.insertMailboxMessageSchema>;
export type MailboxParticipant = typeof base.mailboxParticipants.$inferSelect;
export type InsertMailboxParticipant = z.infer<typeof base.insertMailboxParticipantSchema>;
export type Notification = typeof base.notifications.$inferSelect;
export type InsertNotification = z.infer<typeof base.insertNotificationSchema>;
export type PushDevice = typeof base.pushDevices.$inferSelect;
export type InsertPushDevice = z.infer<typeof base.insertPushDeviceSchema>;
export type MailboxMessageAudit = typeof base.mailboxMessageAudit.$inferSelect;
export type InsertMailboxMessageAudit = z.infer<typeof base.insertMailboxMessageAuditSchema>;
export type CommunicationSettings = typeof base.communicationSettings.$inferSelect;
export type InsertCommunicationSettings = z.infer<typeof base.insertCommunicationSettingsSchema>;
export type GlobalSettings = typeof base.globalSettings.$inferSelect;
export type InsertGlobalSettings = z.infer<typeof base.insertGlobalSettingsSchema>;
export type SystemConfig = typeof base.systemConfig.$inferSelect;
export type InsertSystemConfig = z.infer<typeof base.insertSystemConfigSchema>;
export type LoginCredentials = z.infer<typeof base.loginSchema>;
export type UserLoginHistory = typeof audit.userLoginHistory.$inferSelect;
export type InsertUserLoginHistory = z.infer<typeof audit.insertUserLoginHistorySchema>;
export type UserAccountEvent = typeof audit.userAccountEvents.$inferSelect;
export type InsertUserAccountEvent = z.infer<typeof audit.insertUserAccountEventSchema>;
export type UserAdminNote = typeof audit.userAdminNotes.$inferSelect;
export type InsertUserAdminNote = z.infer<typeof audit.insertUserAdminNoteSchema>;
export type UserSession = typeof base.userSessions.$inferSelect;
export type InsertUserSession = z.infer<typeof audit.insertUserSessionSchema>;
export type RememberMeToken = typeof base.rememberMeTokens.$inferSelect;
export type InsertRememberMeToken = z.infer<typeof audit.insertRememberMeTokenSchema>;
export type TraderJournal = typeof audit.traderJournal.$inferSelect;
export type InsertTraderJournal = z.infer<typeof audit.insertTraderJournalSchema>;
export type AdminAction = typeof audit.adminActions.$inferSelect;
export type InsertAdminAction = z.infer<typeof audit.insertAdminActionSchema>;
export type MigrationExportJob = typeof audit.migrationExportJobs.$inferSelect;
export type MigrationImportJob = typeof audit.migrationImportJobs.$inferSelect;
export type MigrationJobLog = typeof audit.migrationJobLogs.$inferSelect;
export type MigrationIdMap = typeof audit.migrationIdMap.$inferSelect;
export type MigrationIntegrityCheck = typeof audit.migrationIntegrityChecks.$inferSelect;
export type UserVerification = typeof identity.userVerification.$inferSelect;
export type InsertUserVerification = z.infer<typeof identity.insertUserVerificationSchema>;
export type EmailVerificationToken = typeof identity.emailVerificationTokens.$inferSelect;
export type InsertEmailVerificationToken = z.infer<typeof identity.insertEmailVerificationTokenSchema>;
export type SmsOtpToken = typeof identity.smsOtpTokens.$inferSelect;
export type InsertSmsOtpToken = z.infer<typeof identity.insertSmsOtpTokenSchema>;
export type UserEquityDaily = typeof identity.userEquityDaily.$inferSelect;
export type InsertUserEquityDaily = z.infer<typeof identity.insertUserEquityDailySchema>;
export type UserMfa = typeof identity.userMfa.$inferSelect;
export type InsertUserMfa = z.infer<typeof identity.insertUserMfaSchema>;
export type UserKycProfile = typeof identity.userKycProfiles.$inferSelect;
export type InsertUserKycProfile = z.infer<typeof identity.insertUserKycProfileSchema>;
export type UserPayoutProfile = typeof identity.userPayoutProfiles.$inferSelect;
export type InsertUserPayoutProfile = z.infer<typeof identity.insertUserPayoutProfileSchema>;
export type IdentityAuditEvent = typeof identity.identityAudit.$inferSelect;
export type InsertIdentityAuditEvent = z.infer<typeof identity.insertIdentityAuditSchema>;
export type GriftIdentityLink = typeof grift.griftIdentityLinks.$inferSelect;
export type InsertGriftIdentityLink = z.infer<typeof grift.insertGriftIdentityLinkSchema>;
export type GriftAlert = typeof grift.griftAlerts.$inferSelect;
export type InsertGriftAlert = z.infer<typeof grift.insertGriftAlertSchema>;
export type GriftUserRisk = typeof grift.griftUserRisk.$inferSelect;
export type InsertGriftUserRisk = z.infer<typeof grift.insertGriftUserRiskSchema>;
export type GriftLinkedAccountEdge = typeof grift.griftLinkedAccountEdges.$inferSelect;
export type InsertGriftLinkedAccountEdge = z.infer<typeof grift.insertGriftLinkedAccountEdgeSchema>;
export type GriftConfig = typeof grift.griftConfig.$inferSelect;
export type InsertGriftConfig = z.infer<typeof grift.insertGriftConfigSchema>;
export type GriftDevice = typeof grift.griftDevices.$inferSelect;
export type InsertGriftDevice = z.infer<typeof grift.insertGriftDeviceSchema>;
export type GriftDeviceUser = typeof grift.griftDeviceUsers.$inferSelect;
export type InsertGriftDeviceUser = z.infer<typeof grift.insertGriftDeviceUserSchema>;
export type GriftSignal = typeof grift.griftSignals.$inferSelect;
export type InsertGriftSignal = z.infer<typeof grift.insertGriftSignalSchema>;

// Legal compliance types
export type LegalDocument = typeof legal.legalDocuments.$inferSelect;
export type InsertLegalDocument = z.infer<typeof legal.insertLegalDocumentSchema>;
export type LegalDocPointer = typeof legal.legalDocPointers.$inferSelect;
export type InsertLegalDocPointer = z.infer<typeof legal.insertLegalDocPointerSchema>;
export type LegalAcceptance = typeof legal.legalAcceptances.$inferSelect;
export type InsertLegalAcceptance = z.infer<typeof legal.insertLegalAcceptanceSchema>;
export type LegalDocChangeAuditEntry = typeof legal.legalDocChangeAudit.$inferSelect;
export type InsertLegalDocChangeAudit = z.infer<typeof legal.insertLegalDocChangeAuditSchema>;

// Daily FX closes types
export type DailyFxClose = typeof legal.dailyFxCloses.$inferSelect;
export type InsertDailyFxClose = z.infer<typeof legal.insertDailyFxCloseSchema>;
