apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: tradehub
spec:
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: tradehub
spec:
  serviceName: valkey
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.0.1@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
          ports:
            - containerPort: 6379
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
            - "--maxmemory"
            - "1gb"
            - "--maxmemory-policy"
            - "allkeys-lru"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: valkey-data
          emptyDir: {}
