apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tradehub
  namespace: argocd
spec:
  description: TradeHub GitOps project
  sourceRepos:
    - "*"
  destinations:
    - namespace: tradehub
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
