{
 "title": "PGCAT Instance",
 "description": "PostgreSQL Catalog Explorer for Single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn:text}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn:text}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn:text}';" },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} ,ip)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "type": "stat",
   "description": "Replication Facts about this instance: In recovery, In sync commit mode, has replication descendant. has publication, has subscription",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_in_recovery{ins=\"$ins\"}",
     "legendFormat": "recovery"
    },
    {
     "expr": "pg_recv_init_lsn{ins=\"$ins\"} > bool 0",
     "legendFormat": "{{ sender_host }}"
    },
    {
     "expr": "pg_sync_standby_enabled{ins=\"$ins\"}",
     "legendFormat": "sync"
    },
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "children"
    },
    {
     "expr": "count by (ins)(pg_pubrel_count{ins=\"$ins\"}) > bool 0 or on() vector(0)",
     "legendFormat": "pub"
    },
    {
     "expr": "count by (ins)(pg_sub_id{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (SELECT count(*) AS databases FROM pg_database) d,\n     (SELECT count(*) AS roles FROM pg_roles) r,\n     (SELECT count(*) AS tablespaces FROM pg_tablespace) tsp\n    -- (SELECT count(*) AS session FROM pg_stat_activity) proc,\n    -- (SELECT current_setting('max_connections')::INTEGER AS maxconn) mc\n;"
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{job=\"pgsql\", cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT version();" }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid::INTEGER, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Activity",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT pg_blocking_pids(pid) AS blocking_pids,\n       datid,\n       datname,\n       pid,\n       leader_pid,\n       usesysid,\n       usename,\n       application_name,\n       client_addr,\n       client_hostname,\n       client_port,\n       extract(epoch from now() - backend_start) AS conn_time,\n       extract(epoch from now() - xact_start)    AS xact_time,\n       extract(epoch from now() - query_start)   AS query_time,\n       extract(epoch from now() - state_change)  AS state_time,\n       wait_event_type,\n       wait_event,\n       state,\n       backend_xid,\n       backend_xmin,\n       query_id,\n       query,\n       backend_type,\n       query_id::TEXT AS qid -- 14 has query_id, comment this for PG 13 and below \nFROM pg_stat_activity;"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks for ${dsn:text}",
     "type": "table",
     "description": "Block by : Which pid are blocked by this PID ?\n\nBlock N: how many process are blocked by this process?",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "rawSql": "WITH RECURSIVE\n    activity as (select pg_blocking_pids(pid) blocked_by, *,\n                        extract(seconds FROM age(clock_timestamp(), xact_start)) as xact_wait,\n                        extract(seconds FROM age(clock_timestamp(),\n                            -- (select max(l.waitstart) from pg_locks l where a.pid = l.pid)    -- PG 14 and newer\n                             state_change       -- PG 13 and below\n                            )) as lock_wait\n                 -- \"pg_locks.waitstart\" – PG14+ only; for older versions:  age(clock_timestamp(), state_change) as wait_age\n                 from pg_stat_activity a\n                 where state is distinct from 'idle'),\n    blockers as (select array_agg(distinct c order by c) as pids\n                 from (select unnest(blocked_by)\n                       from activity) as dt(c)),\n    tree as (select activity.*,\n                    1                           as level,\n                    activity.pid                as top_blocker_pid,\n                    array [activity.pid]        as path,\n                    array [activity.pid]::int[] as all_blockers_above\n             from activity, blockers\n             where array [pid] <@ blockers.pids and blocked_by = '{}'::int[]\n             union all\n             select activity.*,\n                    tree.level + 1 as level,\n                    tree.top_blocker_pid,\n                    path || array [activity.pid] as path,\n                    tree.all_blockers_above || array_agg(activity.pid) over () as all_blockers_above\n             from activity,\n                  tree\n             where not array [activity.pid] <@ tree.all_blockers_above\n               and activity.blocked_by <> '{}'::int[]\n               and activity.blocked_by <@ tree.all_blockers_above)\nselect pid,\n       blocked_by,\n       case when wait_event_type = 'Lock' then 'waiting' else state end                                      as state,\n       wait_event_type,\n       wait_event,\n       xact_wait,\n       lock_wait,\n       age(backend_xid) AS xid_age,\n       -- 2147483647 - age(backend_xmin) as xmin_ttf,\n       datname, usename, level - 1 AS level,\n       (select count(distinct t1.pid) from tree t1 where array [tree.pid] <@ t1.path and t1.pid <> tree.pid) as blkd,\n       format('%s %s%s', lpad('[' || pid::text || ']', 9, ' '), repeat('.', level - 1) || case when level > 1 then ' ' end, left(query, 1000) ) as query\nfrom tree\nWHERE datname = CURRENT_DATABASE()\norder by top_blocker_pid, level, pid;"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions (by Type)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.backend_type\n\nSystem Processes Included",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch from now()) AS time,\n  coalesce(backend_type, 'null') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY coalesce(backend_type, 'null');"
      }
     ]
    },
    {
     "title": "Sessions (by State)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.state\n\nSystem Processes Included",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch from now()) AS time,\n  coalesce(state, '_system') AS metric,\n  count(*) AS value\nFROM pg_stat_activity\n-- WHERE state IS NOT NULL\nGROUP BY 2;"
      }
     ]
    },
    {
     "title": "Sessions (by Wait Event)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.wait_event_type\n\nSystem Processes Included",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch from now()) AS time,\n  coalesce(wait_event, 'Running') as metric,\n  count(*) as value\nFROM pg_stat_activity\nGROUP BY 2;"
      }
     ]
    },
    {
     "title": "Sessions (by Client Addr)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.client_addr/client_port\n\nSystem Processes Excluded",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT now() AS time, metric AS metric, value FROM\n(SELECT coalesce(host(client_addr),'') || CASE client_port WHEN -1 THEN 'unix socket' ELSE ':' || client_port::TEXT END AS metric, count(*) AS value \nFROM pg_stat_activity WHERE state IS NOT NULL GROUP BY 1);"
      }
     ]
    },
    {
     "title": "Sessions (by User)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.usename\n\nSystem Processes Excluded",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch from now()) AS time,\n  coalesce(usename, '_system') as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE state IS NOT NULL\nGROUP BY 2;"
      }
     ]
    },
    {
     "title": "Sessions (by App)",
     "type": "piechart",
     "description": "Session group by pg_stat_activity.application_name\n\nSystem Processes Excluded",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch from now()) AS time,\n  CASE application_name WHEN '' THEN  'unknown' ELSE application_name END as metric,\n  count(*) as value\nFROM pg_stat_activity\nWHERE state IS NOT NULL\nGROUP BY 2;"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top SQL by Time",
     "type": "table",
     "description": "pg_stat_statements of instance ${ins}, order by total_exec_time DESC.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Roles of this database",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 159 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT r.oid, r.rolname, r.rolsuper, r.rolinherit,\n       r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,\n       r.rolconnlimit, -- r.rolvaliduntil,\n       ARRAY(SELECT b.rolname\n             FROM pg_catalog.pg_auth_members m\n                      JOIN pg_catalog.pg_roles b ON (m.roleid = b.oid)\n             WHERE m.member = r.oid) as memberof\n        , pg_catalog.shobj_description(r.oid, 'pg_authid') AS description\n        , r.rolreplication\n        , r.rolbypassrls\nFROM pg_catalog.pg_roles r\nWHERE r.rolname !~ '^pg_'\nORDER BY 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postmaster",
     "type": "stat",
     "description": "These settings can only be applied when the server starts",
     "gridPos": { "h": 22, "w": 6, "x": 0, "y": 171 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT extract(EPOCH FROM now()) AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'postmaster'"
      }
     ]
    },
    {
     "title": "Internal",
     "type": "stat",
     "description": "These settings cannot be changed directly; they reflect internally determined values. Some of them may be adjustable by rebuilding the server with different configuration options, or by changing options supplied to initdb.",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 171 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT extract(EPOCH FROM now()) AS time, name AS metric,setting AS value FROM pg_settings WHERE context = 'internal' AND\nname NOT LIKE 'polar%'"
      }
     ]
    },
    {
     "title": "Changed",
     "type": "table",
     "description": "These settings that has non-default values",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT name,setting,source,context,pending_restart FROM pg_settings;"
      }
     ]
    },
    {
     "title": "Init Parameters",
     "type": "stat",
     "description": "Info from pg_control_system",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 184 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_init();"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Archive Command & Primary Info",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT extract(EPOCH FROM now()) AS time, name AS metric,setting AS value FROM pg_settings WHERE name = 'archive_command' or name = 'primary_conninfo';"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Stats",
     "type": "table",
     "description": "The pg_stat_replication view will contain one row per WAL sender process, showing statistics about replication to that sender's connected standby server. Only directly connected standbys are listed; no information is available about downstream standby servers.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 196 },
     "targets": [
      {
       "rawSql": "SELECT application_name                                                 AS appname,\n       usename,\n       coalesce(abbrev(client_addr), 'localhost') || ':' || client_port AS address,\n       pid,\n       state,\n       sync_state,\n       sync_priority,\n       backend_xmin::TEXT::BIGINT                                       AS backend_xmin,\n       current.lsn - '0/0'                                              AS lsn,\n       current.lsn - sent_lsn                                           AS sent_diff,\n       current.lsn - write_lsn                                          AS write_diff,\n       current.lsn - flush_lsn                                          AS flush_diff,\n       current.lsn - replay_lsn                                         AS replay_diff,\n       coalesce(extract(EPOCH FROM write_lag), 0)                       AS write_lag,\n       coalesce(extract(EPOCH FROM flush_lag), 0)                       AS flush_lag,\n       coalesce(extract(EPOCH FROM replay_lag), 0)                      AS replay_lag,\n       extract(EPOCH FROM current_timestamp)                            AS \"time\",\n       extract(EPOCH FROM backend_start)                                AS launch_time,\n       extract(EPOCH FROM reply_time)                                   AS reply_time\nFROM pg_stat_replication,\n     (SELECT CASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END AS lsn) current;"
      }
     ]
    },
    {
     "title": "Replication Slots (Physical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 202 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'physical';"
      }
     ]
    },
    {
     "title": "Replication Slots (Logical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 208 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'logical';"
      }
     ]
    },
    {
     "title": "WAL Receiver (Replica Only)",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 214 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_wal_receiver;"
      }
     ]
    },
    {
     "title": "Subscription",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 214 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_subscription;"
      }
     ]
    },
    {
     "title": "Publication",
     "type": "stat",
     "description": "Publication Information",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 214 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_publication;" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 229 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(name, 'Free') AS name, off AS offset, allocated_size AS size FROM pg_shmem();"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "piechart",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "rawSql": "SELECT extract(EPOCH FROM now()) AS time, coalesce(name, 'Free') AS name, allocated_size AS size FROM pg_shmem() ORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "pg_shmem",
     "type": "marcusolsson-treemap-panel",
     "description": "PostgreSQL server's main shared memory segment.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 239 },
     "targets": [
      {
       "rawSql": "SELECT extract(EPOCH FROM now()) AS time, coalesce(name, 'Free') AS name, allocated_size AS size FROM pg_shmem() ORDER BY 2 DESC;"
      }
     ]
    },
    {
     "title": "pg_stat_slru",
     "type": "table",
     "description": "PostgreSQL accesses certain on-disk information via SLRU (simple least-recently-used) caches. The pg_stat_slru view will contain one row for each tracked SLRU cache, showing statistics about access to cached pages.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 239 },
     "targets": [
      {
       "rawSql": "SELECT name,blks_zeroed,blks_hit,blks_read,blks_written,blks_exists,flushes,truncates FROM pg_stat_slru"
      }
     ]
    }
   ]
  },
  {
   "title": "Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(((system_identifier>>32) & (2^32 -1)::bigint))::TEXT AS \"Cluster Created At\" FROM pg_control_system();"
      }
     ]
    },
    {
     "title": "pg_control_system",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 250 },
     "targets": [
      {
       "rawSql": "SELECT \npg_control_version,\ncatalog_version_no,\nsystem_identifier\t,\nextract(EPOCH FROM pg_control_last_modified) * 1000 AS last_modified\nFROM pg_control_system();"
      }
     ]
    },
    {
     "title": "pg_stat_wal",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n wal_records      ,\n wal_fpi          ,\n wal_bytes        ,\n wal_buffers_full ,\n wal_write        ,\n wal_sync         ,\n wal_write_time   ,\n wal_sync_time    \nFROM pg_stat_wal;"
      }
     ]
    },
    {
     "title": "pg_stat_bgwriter / checkpointer",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_bgwriter;"
      },
      {
       "rawSql": "SELECT * FROM pg_stat_checkpointer;"
      }
     ]
    },
    {
     "title": "pg_control_checkpoint",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 252 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n    checkpoint_lsn,\n    redo_lsn,\n    redo_wal_file,\n    timeline_id,\n    prev_timeline_id,\n    full_page_writes,\n    next_xid,\n    next_oid,\n    next_multixact_id,\n    next_multi_offset,\n    oldest_xid,\n    oldest_xid_dbid,\n    oldest_active_xid,\n    oldest_multi_xid,\n    oldest_multi_dbid,\n    oldest_commit_ts_xid,\n    newest_commit_ts_xid,\n    checkpoint_time::text\nFROM pg_control_checkpoint();"
      }
     ]
    },
    {
     "title": "pg_control_recovery",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 258 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_control_recovery();"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "pgBackRest Backup Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 267 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pgbackrest\nWHERE name = '${cls}';"
      }
     ]
    }
   ]
  },
  {
   "title": "Patroni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Patroni Conf",
     "type": "table",
     "gridPos": { "h": 16, "w": 10, "x": 0, "y": 278 },
     "targets": [
      {
       "rawSql": "SELECT key, value FROM patroni_conf d, jsonb_each(d.data)  WHERE key != 'postgresql' ;\n-- WHERE name = '${cls}';"
      }
     ]
    },
    {
     "title": "PostgreSQL Parameters",
     "type": "table",
     "gridPos": { "h": 16, "w": 14, "x": 10, "y": 278 },
     "targets": [
      {
       "rawSql": "SELECT key, value FROM (SELECT value->'parameters' AS v FROM patroni_conf d, jsonb_each(d.data)  WHERE key = 'postgresql') p, jsonb_each(p.v);"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Status",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 295 },
     "targets": [
      {
       "rawSql": "SELECT * FROM process_status;\n-- WHERE name = '${cls}';"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 311 },
     "targets": [
      { "rawSql": "SELECT * FROM disk_free;" }
     ]
    }
   ]
  }
 ]
}