apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - tradehub-secrets.sops.yaml
images:
  - name: registry.equitywaves.com/tradehub/app
    newName: ghcr.io/REPLACE_GITHUB_ORG/tradequip
    newTag: git-bootstrap
patches:
  - path: patch-configmap.yaml
  - path: patch-ingress.yaml
  - path: patch-runtime.yaml
